dist: bionic

jobs:
  include:
    - stage: test
      language: go
      go: "1.13.10"
      script: go test -gcflags=-l -v ./...

    - stage: build
      language: minimal
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - export REPO="${TRAVIS_REPO_SLUG,,}"
        - docker build -t $REPO:latest .
        - docker push $REPO:latest

    - stage: build_tag
      language: minimal
      script:
        - export REPO="${TRAVIS_REPO_SLUG,,}"
        - export TAG="${TRAVIS_TAG/v/}"
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t $REPO:latest-tag-release .
        - docker tag $REPO:latest-tag-release $REPO:$TAG
        - docker push $REPO:latest-tag-release
        - docker push $REPO:$TAG

    - stage: deploy_tag
      language: minimal
      env:
        - NAMESPACE="wejay"
        - DEPLOYMENT="gen-cover"
        - CONTAINER="gen-cover"
        - DEPLOY_SCRIPT="https://gist.githubusercontent.com/ankjevel/fc444cdb248287a97242ced271ece388/raw/69f469562ebe46ef15e066fc574d5d865a5e83ee/deploy.sh"
      script:
        - export REPO="${TRAVIS_REPO_SLUG,,}"
        - export TAG="${TRAVIS_TAG/v/}"
        - source <(curl "$DEPLOY_SCRIPT" -s 2>&1)

stages:
  - name: test
  - name: build
    if: branch = master AND type != pull_request AND tag !~ /^v/
  - name: build_tag
    if: tag =~ /^v/
  - name: deploy_tag
    if: tag =~ /^v/

notifications:
  email: false
